name: Hammel
options:
  bundleIdPrefix: com.fahad
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  Hammel:
    type: application
    platform: iOS
    sources:
      - V11
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fahad.Hammel
        PRODUCT_NAME: Hammel
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: "مُحمّل"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_NSPhotoLibraryAddUsageDescription: "يحتاج مُحمّل إلى إذن لإضافة الفيديوهات والصور التي تختار حفظها إلى مكتبة الصور."
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "يحتاج مُحمّل للوصول إلى الصور والفيديوهات التي تختار استيرادها إلى مكتبة التطبيق."
        INFOPLIST_KEY_NSCameraUsageDescription: "يستخدم مُحمّل الكاميرا فقط عندما تختار التقاط صورة لإضافتها إلى المكتبة."
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
