name: Hammel
options:
  bundleIdPrefix: com.fahad
  deploymentTarget:
    iOS: "17.0"
packages:
  SwiftMP3:
    url: https://github.com/mierau/swift-mp3.git
    branch: main
settings:
  base:
    SWIFT_VERSION: 5.10
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  Hammel:
    type: application
    platform: iOS
    sources:
      - V11
    dependencies:
      - package: SwiftMP3
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fahad.Hammel
        PRODUCT_NAME: Hammel
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: V11/Info.plist
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
