name: FPSConverter
options:
  bundleIdPrefix: com.fahad
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: 5.9
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: NO
    SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
targets:
  FPSConverter:
    type: application
    platform: iOS
    sources: [FPSConverter]
    info:
      path: FPSConverter/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.fahad.screenflow
        PRODUCT_NAME: ScreenFlow
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_OBJC_BRIDGING_HEADER: FPSConverter/FPSConverter-Bridging-Header.h
        CLANG_ENABLE_MODULES: YES
